/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:7a2883c6-680b-4b52-a058-f5dea84d491f",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_yn50bPi5e",
    "aws_user_pools_web_client_id": "6vu05hk6tv121e260rmdv2v9jl",
    "oauth": {}
};


export default awsmobile;
