/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:d27ad22a-8506-473a-95bc-9c633d51eaaf",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_fjsHDcGof",
    "aws_user_pools_web_client_id": "5j8dm0ektndf5ts34qgk0uk3r4",
    "oauth": {}
};


export default awsmobile;
